name: ReddoLib
author: Yakumo_Reddo
version: 1.0
main: com.satsukirin.ReddoLib.PluginMain
api-version: 1.13
commands:
    rl:
        description: ReddoLib.
        usage: /rl help
    reddolib:
        description: ReddoLib.
        usage: /rl help